---

- name: 'Make sure the {{ ca_certs_dir }} is present'
  file:
    state: directory
    path: '{{ ca_certs_dir }}'
    owner: root
    group: root
    mode: 0755
  become: yes

- name: 'Generate certs for infra server || CA server'
  shell: 'openssl genrsa -out {{ item }}-priv-key.pem 2048'
  args:
    chdir: '{{ ca_certs_dir }}'
  become: yes
  with_inventory_hostnames: infra_instances:!localhost

- name: 'Create certificate request for infra server || CA server'
  shell: >
    openssl req -subj '/CN={{ item }}'
    -new -key {{ item }}-priv-key.pem -out {{ item }}.csr
  args:
    chdir: '{{ ca_certs_dir }}'
  become: yes
  with_inventory_hostnames: infra_instances:!localhost

- name: 'Generate the CA trusted certificate'
  shell: >
    openssl x509 -req -days 1825 -in {{ item }}.csr
    -CA ca.pem
    -CAkey ca-priv-key.pem
    -CAcreateserial -out {{ item }}-cert.pem
    -extensions v3_req -extfile /usr/lib/ssl/openssl.cnf
  args:
    chdir: '{{ ca_certs_dir }}'
  become: yes
  with_inventory_hostnames: infra_instances:!localhost

# vim: ft=ansible :
