---
- name: "copy keys from infra to ansible machine for distribution"
  fetch: src="{{ ca_certs_dir }}/{{ item.ssl_key }}" dest="{{ ca_distribution_certs_dir }}/{{ item.ssl_key }}" flat=yes
  with_items:
  - "{{ shelleg_hosts.infra }}"
  - "{{ shelleg_hosts.ci }}"
  - "{{ shelleg_hosts.swarm.swarm_workers }}"
  - "{{ shelleg_hosts.swarm.swarm_managers }}"

- name: "copy certs from infra to ansible machine for distribution"
  fetch: src="{{ ca_certs_dir }}/{{ item.ssl_cert }}" dest="{{ ca_distribution_certs_dir }}/{{ item.ssl_cert }}" flat=yes
  with_items:
  - "{{ shelleg_hosts.infra }}"
  - "{{ shelleg_hosts.ci }}"
  - "{{ shelleg_hosts.swarm.swarm_workers }}"
  - "{{ shelleg_hosts.swarm.swarm_managers }}"

- name: "copy ca.pem ca-priv-key.pem"
  fetch: src="{{ ca_certs_dir }}/{{ item }}" dest="{{ ca_distribution_certs_dir }}/{{ item }}" flat=yes
  with_items:
  - "{{ ca_cert }}"
  - "{{ ca_key }}"
  - wildcard-cert.pem