---

- name: "Copy keys from ca-all to ansible machine for distribution"
  fetch:
    src: "{{ ca_certs_dir }}/{{ item }}-priv-key.pem"
    dest: "{{ ca_distribution_certs_dir }}/{{ item }}-priv-key.pem"
    flat: yes
  with_inventory_hostnames: ca-all:!localhost

- name: "Copy certs from ca-all to ansible machine for distribution"
  fetch:
    src: "{{ ca_certs_dir }}/{{ item }}-cert.pem"
    dest: "{{ ca_distribution_certs_dir }}/{{ item }}-cert.pem"
    flat: yes
  with_inventory_hostnames: ca-all:!localhost

- name: "Copy ca.pem ca-priv-key.pem"
  fetch:
    src: "{{ ca_certs_dir }}/{{ item }}"
    dest: "{{ ca_distribution_certs_dir }}/{{ item }}"
    flat: yes
  with_items:
    - "{{ ca_cert }}"
    - "{{ ca_key }}"
    - "{{ ca_domain }}-wildcard-cert.pem"
    - "{{ ca_domain }}-wildcard-priv-key.pem"

# vim: ft=ansible :
